language: python
python:
  - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-vtk python-nibabel python-numpy python-gtk2 python-gtkglext1
    - sudo apt-get install python-pip
install:
    - python setup.py build
    - python setup.py install
# command to run tests, e.g. python setup.py test
script: nosetests pylocator/tests
